<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>47bf6221-f350-46d1-9fa4-44db3511f741</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\IssueSense.Application.csproj" />
    <ProjectReference Include="..\..\Data\Infrastructure\IssueSense.Infrastructure.csproj" />
  </ItemGroup>

</Project>
