<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\App\Application\IssueSense.Application.csproj" />
    <ProjectReference Include="..\..\Data\Infrastructure\IssueSense.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Datasets\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
