using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueSense.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Reconciles the EF model with the "onwers" table. On the original database it already
    /// existed (created manually, outside migrations - see docs/DEVELOPMENT.md), so this is a
    /// no-op there; CREATE TABLE IF NOT EXISTS also makes it correctly create the table from
    /// scratch on any other database (a fresh clone, CI, Testcontainers) that runs the full
    /// migration set instead. Column shape matches the pre-existing table exactly.
    /// </summary>
    public partial class AddOwnersModelSnapshot : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS onwers (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name character varying(256) NOT NULL,
                    created_date timestamp without time zone,
                    changed_date timestamp without time zone
                );
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS onwers;");
        }
    }
}
